### ISSUE TITLE
Diagrama de bloques de Subsistema de despliegue de código decodificado en display de 7 segmentos.

### ISSUE THREAD

**Issue by Siuuuuuuu07** [Lauritabrenes/Proyecto-II-Introduccion-a-diseno-digital-en-HDL#6]
Este subsistema toma los datos para los 4 dígitos de un bloque de 7 segmentos. El sistema deberá tener
la tasa de refresco adecuada para una visualización cómoda por parte del usuario

**Comment by Lauritabrenes** [comment]
![Image](https://user-images.githubusercontent.com/111261878/233260758-35800b30-6603-4ba4-a410-6b9c74c7a31f.jpg)
